{% set name = "casacore" %}
{% set version = "2.4.0" %}
{% set sha256 = "9ae749d604d037a5a7b13b9eb759dfb8e22a405dcdb61f67c0916d3fe78db39c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ncursesw.patch
    - default-root.patch
    - so-versioning.patch
    - boost-python.patch  # [not py3k]
    - boost-python3.patch  # [py3k]

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [osx]
    - flex
    - bison
    - boost 1.65.1
    - cfitsio 3.410
    - cmake
    - fftw 3.3.*
    - hdf5 1.10.1
    - ncurses 5.9
    - numpy
    - openblas 0.2.19|0.2.19.*
    - python
    - readline 6.2*
    - wcslib 5.16
  run:
    - boost 1.65.1
    - cfitsio 3.410
    - fftw 3.3.*
    - hdf5 1.10.1
    - libgfortran  # [unix]
    - ncurses 5.9
    - numpy
    - openblas 0.2.19|0.2.19.*
    - python
    - readline 6.2*
    - wcslib 5.16

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  license_file: COPYING
  summary: 'Core libraries for the Common Astronomical Software Applications (CASA)'

extra:
  recipe-maintainers:
    - pkgw
