{% set name = "casacore" %}
{% set version = "2.3.1a1" %}
#{% set sha256 = "d8ed5373f5447885be6d3aac72f26cee24a662df5caf4a6cd23e846b79181700" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  git_url: https://github.com/casacore/casacore.git
  git_rev: 05be37c02bc3a18aaef0477c7bb35dbc528edaca # last commit that master and casa-5.1.0 have in common
  patches:
    - ncursesw.patch
    - default-root.patch
    - so-versioning.patch
    - boost-python.patch  # [not py3k]
    - boost-python3.patch  # [py3k]

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [osx]
    - flex
    - bison
    - boost 1.65.1
    - cfitsio 3.410
    - cmake
    - fftw 3.3.*
    - hdf5 1.8.18|1.8.18.*
    - ncurses 5.9
    - numpy
    - openblas 0.2.19|0.2.19.*
    - python
    - readline 6.2*
    - wcslib 5.16
  run:
    - boost 1.65.1
    - cfitsio 3.410
    - fftw 3.3.*
    - hdf5 1.8.18|1.8.18.*
    - libgfortran  # [unix]
    - ncurses 5.9
    - numpy
    - openblas 0.2.19|0.2.19.*
    - python
    - readline 6.2*
    - wcslib 5.16

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  license_file: COPYING
  summary: 'Core libraries for the Common Astronomical Software Applications (CASA)'

extra:
  recipe-maintainers:
    - pkgw
