{% set name = "casacore" %}
{% set version = "2.4.2a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  #sha256: "58eccc875053b2c6fe44fe53b6463030ef169597ec29926936f18d27b5087d63"
  git_url: https://github.com/casacore/casacore.git
  git_rev: 1c22f8e4c
  patches:
    - ncursesw.patch
    - default-root.patch
    - so-versioning.patch
    - boost-python.patch
    - ignore-build-env-prefix.patch
    - array-templates.patch
    - clang-link.patch  # [osx]

build:
  number: 1010
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('casacore', max_pin='x.x') }}

requirements:
  build:
    - bison
    - cmake
    - flex
    - m4
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - boost
    - cfitsio
    - fftw 3.3.*
    - hdf5
    - ncurses
    - numpy
    - python
    - readline
    - wcslib 5.20.*
  run:
    - boost
    - fftw 3.3.*
    - hdf5
    - ncurses
    - {{ pin_compatible('numpy') }}
    - python
    - readline
    - wcslib 5.20.*

test:
  commands:
    - casahdf5support
    - findmeastable --help
    - lsmf
    - measuresdata
    - taql --help
    - tomf --help

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  license_file: COPYING
  summary: 'Core libraries for the Common Astronomical Software Applications (CASA)'

extra:
  recipe-maintainers:
    - pkgw
