travis:
  secure:
    BINSTAR_TOKEN: lXbanRO2PIIkw6fon8O5NSRra6OLPlmsr7IUm5P2osi5DIBvuMllEcvtWqXUnQzcub0M1gGjBGOFSECPPaxI/ozq1IYrsGssSY73eOTG8pk9eaebThC06E5euGvFb5vGnzGFlFXY8escKAssUDfdRE33x6B6MCiohgt65xFLLPuNbqS37oUPRyTXVjBTvCh0c5vWsfkOApRmLzr1Dqeg1ISfu5x9s5xNxvcIYuiKYf0YdZjQzeiLeNRspLa09wpKfN6SNzCyKwo3hvH7l/nKMqYU/oHtY5ZkM8NkpsaT3CoffD0pBXTwzycQ8b26KhOFsRt0n0EJC+FNL73URqscGLt6f+tw5+GogQ0ojfD1lqQpRJhKML2edJnZcbT7WpXODV/WTtIWj8MfFlJp0SuSjCb7WTPYDusoxsyZgSljNjvK22cTFjoq7SNdtXssANBJuXXmw2sslZ+CWSpzD3JNkbQE2j2hQDPl7UMaRYtioxGQKuHpxaXEQPNtZWyLezcln4wMjKxV9EmfjWEoWxa2twL66WYC1L+qjAHARPRwybSzw7bU34Yt0D7nxScbaXOQg+joQspr6jDTNKDIfhUETMhGXHQEkFNTxnZOlnWU34s50DpNJqUKRFeC2g5YM4Cpbwq8oTANUDd8pb4/L3oeD+PhWhYVYW8jimh1svObBuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
